const TRANSACTION_FEE = 1;
const INITIAL_BALANCE = 100;
const VALIDATOR_FEE = 30;
const TRANSACTION_THRESHOLD = 5;


module.exports = {
    TRANSACTION_FEE,
    INITIAL_BALANCE,
    VALIDATOR_FEE,
    TRANSACTION_THRESHOLD
}